services:
  dns-webui:
    image: kevinvobw/dns-webui
    container_name: dns-webui
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
      - "80:80"
      - "443:443"
    volumes:
      - ./bind/etc:/etc/bind
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
